version: '2'
services:
  webapp:
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /webodm/wait-for-it.sh db:5432 -- /webodm/start.sh --create-default-pnode --setup-devenv"
    volumes:
      - .:/webodm
